import React, { Component } from 'react'
import { NavLink, withRouter } from 'react-router-dom'
import { connect } from 'react-redux'
import { getAccounts } from '../actions/index'

class Header extends Component {
  componentDidMount () {
    this.props.getAccounts()
  }

  renderAccounts () {
    return this.props.accounts.map(account => {
      return (
        <li key={account.id}><NavLink activeClassName="is-active" to={`/account/${account.name}`}>{account.name}</NavLink></li>
      )
    })
  }

  render () {
    return (
      <div className="hero-head">
        <header>
          <div className="container">
            <div className="section">
              <div className="has-text-centered">
                <h1 className="title is-1 is-spaced">Kenny Cunanan</h1>
                <h4 className="subtitle is-4">a simple blog generated by Medium</h4>
              </div>
            </div>
            <div className="section">
              <div className="tabs is-centered">
                <ul>
                  <li><NavLink exact activeClassName="is-active" to="/">Home</NavLink></li>
                  {this.renderAccounts()}
                  <li><NavLink activeClassName="is-active" to="/about">About</NavLink></li>
                  <li><NavLink activeClassName="is-active" to="/contact">Contact</NavLink></li>
                </ul>
              </div>
            </div>
          </div>
        </header>
      </div>
    )
  }
}

function mapStateToProps (state) {
  return {
    accounts: state.accounts
  }
}

export default withRouter(connect(mapStateToProps, { getAccounts })(Header))
